### ISSUE TITLE
How to generate OPTIC_TOKEN  ?

### ISSUE THREAD

**Issue by ikenna** [opticdev/github-action#7]
I have logged in to [app.useoptic.com](https://app.useoptic.com/) (authenticating via Github), but I can see no information there on how to generate a token. Please what am I missing?

**Comment by acunniffe** [comment]
Hey @ikenna -- we recently updated Optic Cloud to work as a GitHub application. You no longer need to manually set the token or the use the GitHub action. 

Go to the Setting Tab and hit "Configure" to set the GitHub permissions. 

Then go to the APIs tab and hit "Sync" - Optic will discover the OpenAPI specs and help you add various rules to them. 

Let me know if you need any more help.

**Comment by ikenna** [comment]
Got it. Thank you @acunniffe.
